version: "3.9"
services:
  web:
    build: .
    ports:
      - "8081:8081"
    depends_on:
      - db
  redis:
    image: "redis:alpine"
  db:
    image: mysql:5.7.22
    restart: always
    environment:
        MYSQL_DATABASE: Catalog
        MYSQL_USER: root
        MYSQL_PASSWORD: root
        MYSQL_ROOT_PASSWORD: root
    values: 
      - .dbdata:/var/lib/mysql
    ports:
      - 33060:3306 
